import {
  // ExclamationTriangleIcon as ErrorIconMini,
  CheckCircleIcon as CheckCircleIconMini,
  EyeIcon as EyeIconMini,
  EyeSlashIcon as EyeSlashIconMini,
  InformationCircleIcon as InformationCircleIconMini,
  NoSymbolIcon as Blocking,
  CheckCircleIcon as CheckIconMini,
  ChevronDownIcon as ChevronDownIconMini,
  AdjustmentsHorizontalIcon as ViewIcon,
  GlobeAltIcon as GlobalIcon,
  MagnifyingGlassIcon as MagnifyingGlassIconOutline,
  ArrowRightStartOnRectangleIcon,
} from "@heroicons/react/20/solid";
import {
  // UserIcon as UserIcon,
  EyeSlashIcon,
  EyeIcon,
  PhotoIcon as ImageIcon,
  CheckIcon as CheckIconOutline,
  Bars3CenterLeftIcon as SidebarIcon,
  ExclamationTriangleIcon as ExclamationTriangleIconOutline,
  CloudArrowUpIcon as CloudIcon,
  CheckCircleIcon as CircleCheck,
  TrashIcon as DeleteIcon,
  PencilSquareIcon as EditIcon,
  PlusIcon as PlusIcon,
  ArrowRightStartOnRectangleIcon as LogIcon
} from "@heroicons/react/24/outline";

export {
  CheckIconOutline,
  EyeIcon,
  EyeIconMini,
  EyeSlashIconMini,
  EyeSlashIcon,
  ChevronDownIconMini,
  CheckIconMini,
  Blocking,
  ImageIcon,
  ViewIcon,
  CheckCircleIconMini,
  ExclamationTriangleIconOutline,
  InformationCircleIconMini,
  GlobalIcon,
  MagnifyingGlassIconOutline,
  CloudIcon,
  CircleCheck,
  SidebarIcon,
  DeleteIcon,
  EditIcon,
  PlusIcon,
  LogIcon
};
