export * from "./Auth/Login";
export * from "./Auth/ForgetPassword";
export * from "./Auth/NewPassword";
export * from "./Auth/OtpPassword";
export * from "./Dashboard/page";
export * from "./Dashboard/profile";
export * from "./Products/page";
export * from "./Reports/page";
export * from "./Payment/page";
export * from "./Payment/PaymentParent";
export * from "./Offers/OfferList";
export * from "./Order/page";
export * from "./Offers/page";
export * from "./Auth/Register";
export * from "./Auth/SuccessRegister";
export * from './Offers/Coupon'
